"""change_market_indices_to_timeseries

Revision ID: 9fc017e185bd
Revises: 69d38a11c48a
Create Date: 2025-10-18 11:29:45.120907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc017e185bd'
down_revision: Union[str, Sequence[str], None] = '69d38a11c48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_filtered_symbols_id'), 'filtered_symbols', ['id'], unique=False)
    op.drop_index(op.f('ix_market_indices_code'), table_name='market_indices')
    op.create_index(op.f('ix_market_indices_code'), 'market_indices', ['code'], unique=False)
    op.create_index('ix_created_at_desc', 'market_indices', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_indices_created_at'), 'market_indices', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_indices_created_at'), table_name='market_indices')
    op.drop_index('ix_created_at_desc', table_name='market_indices')
    op.drop_index(op.f('ix_market_indices_code'), table_name='market_indices')
    op.create_index(op.f('ix_market_indices_code'), 'market_indices', ['code'], unique=1)
    op.drop_index(op.f('ix_filtered_symbols_id'), table_name='filtered_symbols')
    # ### end Alembic commands ###
