"""add_filter_profile_table

Revision ID: b0a8bfb163c1
Revises: 90e4f2ecabee
Create Date: 2025-10-08 21:54:43.136459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a8bfb163c1'
down_revision: Union[str, Sequence[str], None] = '90e4f2ecabee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_filter_profiles_id'), 'filter_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_pinned_symbols_symbol'), table_name='pinned_symbols')
    op.drop_table('pinned_symbols')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_symbols',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('market', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinned_symbols_symbol'), 'pinned_symbols', ['symbol'], unique=1)
    op.drop_index(op.f('ix_filter_profiles_id'), table_name='filter_profiles')
    op.drop_table('filter_profiles')
    # ### end Alembic commands ###
