[server]
# Prevent browser from automatically opening
headless = true

[browser]
# Prevent browser from automatically opening  
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
# Show toolbar in viewer mode (shows hamburger menu)
# Options: "auto", "developer", "viewer", "minimal"
toolbarMode = "viewer"

[theme]
# Use dark theme base
base = "dark"

# Primary accent color for interactive elements
primaryColor = "#54A0FD"

# Font family for all text in the app, except code blocks
# Accepts any CSS font-family value
font = "'Noto Sans KR', sans-serif"
